Updated Docker integration tests.
ArieGato/serilog-sinks-rabbitmq pull request #137
Opened 2024-02-03 00:57 UTC by Pastafarian

Tried running the docker integration tests after pulling the project down to take a closer look, found out they weren't currently working so thought I'd get them updated and passing again. 

Good to see all the recent work on the project!

Updated definitions.json to make the username and password consistent with the integration tests.

Updated images from microsoft/dotnet:2.2-sdk to mcr.microsoft.com/dotnet/sdk:8.0 and rabbitmq:3-management to rabbitmq:3.12.12-management.

Removed net472 as a Framework as it prevents projects from running in a Linux container. Given netstandard2.0 is supported, it's superfluous.

2024-02-04 19:13 UTC, Pastafarian commented
Yes, it's a bit of a pain, but it's possible by runnng the integration tests from a mono container that supports the .NET Framework, then install .NET 6.0 and 8.0 into that container. 

A bit of a faff it turns out. But we do now have a version that multi-targets and now runs the previously removed config tests. 

PR updated!

2024-02-04 19:15 UTC, ArieGato requested changes

2024-02-04 19:15 UTC, ArieGato commented on tests/Serilog.Sinks.RabbitMQ.Tests.Integration/Serilog.Sinks.RabbitMQ.Tests.Integration.csproj
> +        <DefineConstants>$(DefineConstants);NET_FX</DefineConstants>
Indentation is not as it was. I wouldn't expect any change in this file.

2024-02-04 19:15 UTC, ArieGato commented on tests/Serilog.Sinks.RabbitMQ.Tests.Integration/RabbitMQCollection.cs
What's the purpose of this file? Why do we need it?

2024-02-04 19:15 UTC, ArieGato commented on tests/Serilog.Sinks.RabbitMQ.Tests.Integration/ConfigurationExtensionsFixture.cs
I wouldn't expect any changes in this file either.

2024-02-05 13:52 UTC, ArieGato submitted a review, later dismissed

2024-02-05 13:55 UTC, Pastafarian commented
Added RabbitMQCollection.cs in an attempt to fix tests before your update to main made it redundent, now removed. Reverted changes to Serilog.Sinks.RabbitMQ.Tests.Integration.csproj and ConfigurationExtensionsFixture.cs

2024-02-05 13:56 UTC, ArieGato approved these changes

2024-02-05 13:57 UTC, merged