Add API approval tests
ArieGato/serilog-sinks-rabbitmq pull request #144
Opened 2024-02-05 10:54 UTC by sungam3r

fixes #141

2024-02-05 10:56 UTC, sungam3r commented on tests/Serilog.Sinks.RabbitMQ.Tests/Approval/Serilog.Sinks.RabbitMQ.approved.txt
> +namespace Serilog.Sinks.RabbitMQ
@ArieGato As you can see there are a lot of public APIs here that should not be exposed.

2024-02-05 11:02 UTC, sungam3r commented
For now I see 
![изображение](https://github.com/ArieGato/serilog-sinks-rabbitmq/assets/21261007/e9e3977b-0b4e-40de-b202-5c6669e2b122)

If I understand correctly pipeline has not even started because of review settings. So I have no change to fix errors if any - I just don't see them. So I should wait for review. If you are concerned about security, then it is not necessary to require a review. Nobody can just merge change into the repository. Only those who have write access can - owners, collaborators, etc.

2024-02-08 07:25 UTC, sungam3r commented
@ArieGato I resolved conflicts.

2024-02-08 08:04 UTC, ArieGato requested changes

2024-02-08 08:04 UTC, ArieGato commented on tests/Serilog.Sinks.RabbitMQ.Tests/Approval/ApiApprovalTests.cs
> +namespace Destructurama.Attributed.Tests;
Namespace is not correct

2024-02-08 08:04 UTC, ArieGato commented on tests/Serilog.Sinks.RabbitMQ.Tests/Serilog.Sinks.RabbitMQ.Tests.csproj
> +    <PackageReference Include="Shouldly" Version="4.2.1" />
I'm using FluentAssertions. I don't want to use two packages that are doing the same thing.

2024-02-08 08:04 UTC, ArieGato commented on tests/Serilog.Sinks.RabbitMQ.Tests/Approval/Serilog.Sinks.RabbitMQ.approved.txt
> +namespace Serilog.Sinks.RabbitMQ
@sungam3r Most has been fixed in PR https://github.com/ArieGato/serilog-sinks-rabbitmq/pull/142

2024-02-08 10:39 UTC, sungam3r commented on tests/Serilog.Sinks.RabbitMQ.Tests/Serilog.Sinks.RabbitMQ.Tests.csproj
> +    <PackageReference Include="Shouldly" Version="4.2.1" />
They are not for the same thing. Shouldly has `ShouldMatchApproved` method specifically for comparing files and I use this method in `PublicApi_Should_Not_Change_Unintentionally` test. You can see the same approach in the main project https://github.com/serilog/serilog/blob/dev/test/Serilog.ApprovalTests/ApiApprovalTests.cs#L19.

2024-02-08 11:21 UTC, ArieGato commented on tests/Serilog.Sinks.RabbitMQ.Tests/Serilog.Sinks.RabbitMQ.Tests.csproj
> +    <PackageReference Include="Shouldly" Version="4.2.1" />
What I mean is that they are both frameworks for asserting test results.  I really don't want to mix them in other unit tests. There still are some Assert from the Microsoft test library. 

If this functionality is not supported in FluentAssertions then we can evaluate whether we can convert towards Shouldly.

2024-02-08 11:25 UTC, ArieGato approved these changes

2024-02-08 11:32 UTC, ArieGato commented
@sungam3r  There are some conflicts

2024-02-08 14:27 UTC, sungam3r commented
Done.

2024-02-08 14:42 UTC, sungam3r commented on tests/Serilog.Sinks.RabbitMQ.Tests/Serilog.Sinks.RabbitMQ.Tests.csproj
> +    <PackageReference Include="Shouldly" Version="4.2.1" />
#150

2024-02-08 15:00 UTC, merged