Migrate to Shouldly
ArieGato/serilog-sinks-rabbitmq pull request #150
Opened 2024-02-08 14:38 UTC by sungam3r

@ArieGato I will retarget PR after merging #144.

2024-02-08 15:48 UTC, sungam3r commented
I merged changes from `master`. I would like to note that I'm still do not see workflow running. It confuses and prevents from fixing bugs with CI.

2024-02-08 16:08 UTC, ArieGato commented
@sungam3r what can I do to make the ci build fire for you?

2024-02-09 06:09 UTC, sungam3r commented
I think this is because the rule requiring review. Just try to disable it.

2024-02-09 07:33 UTC, ArieGato commented
I think the ci build is missing: on pull_request

2024-02-09 08:10 UTC, sungam3r commented
Right. I have not reviewed workflow files yet.

2024-02-09 12:10 UTC, sungam3r commented on src/Serilog.Sinks.RabbitMQ/Sinks/RabbitMQ/RabbitMQClientConfiguration.cs
> +        Hostnames = config.Hostnames.ToList();
@ArieGato HostNames is list on line 27.

2024-02-09 12:39 UTC, sungam3r commented on Directory.Build.props
> +    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">True</ContinuousIntegrationBuild>
I suggest to move potentially shared configuration into top-level Directory.Build.props file.

2024-02-09 15:31 UTC, ArieGato requested changes

2024-02-09 15:31 UTC, ArieGato commented on .github/workflows/ci-build.yml
> +  Configuration: Debug
The environment should be Release

2024-02-09 16:52 UTC, sungam3r commented on .github/workflows/ci-build.yml
> +  Configuration: Debug
```suggestion
  Configuration: Release
```

2024-02-09 16:53 UTC, sungam3r commented on .github/workflows/ci-build.yml
> +  Configuration: Debug
done

2024-02-09 16:57 UTC, ArieGato approved these changes

2024-02-09 16:58 UTC, merged