Project cleanup Part 3
ArieGato/serilog-sinks-rabbitmq pull request #154
Opened 2024-02-10 06:52 UTC by sungam3r

1. Add StyleCop analyzers and fix diagnostics.
2. Add NRT to all projects in Directory.Build.props.
3. Add files to sln tree.

2024-02-11 07:42 UTC, ArieGato requested changes
Looks good, one question about the gitignore file though.

2024-02-11 07:42 UTC, ArieGato commented on .gitignore
Why are these ignores removed?

2024-02-11 19:00 UTC, sungam3r commented on .gitignore
They all are unrelated to .NET projects.

2024-02-12 06:40 UTC, ArieGato approved these changes

2024-02-12 06:40 UTC, merged